/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class App {

    public static void main(String[] args) {

       // Resturant resturant =new Resturant("KFC");
       // System.out.println(resturant.toString());
//
Review r = new Review("tastyyyy","hayaaa", 4);
////        System.out.println(r.toString());
    //Review r = new Review();
        System.out.println(r.toString());
    }
}
