/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static basiclibrary.Library.*;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
//

    @Test void testRoll_shouldReturnArrayOfSizeEqualToParameter(){
        Library sut = new Library();
        int x=4;
        ArrayList<Integer> result= roll(x);
        assertEquals(4, result.size());

        // Validate each rolled number falls within the range [1, 6]
        for (Integer rolledNumber : result) {
            assertTrue(rolledNumber >= 1 && rolledNumber <= 6);
        }

    }
    @Test void testContainsDublicate_shouldReturnTrueIfArrayHasDuplicatedValue(){
        Library sut = new Library();
        int arr[]={1,2,5,8,1};
        boolean result = containsDuplicate(arr);
        Assertions.assertEquals(true,result);
    }
    @Test void testCalculateAvg_shouldReturnAvgOfArray(){

        Library sut = new Library();
        int arr[]={66, 64, 58, 65, 71, 57, 60};
        double result = calculateAverage(arr);
        Assertions.assertEquals(54,result);

    }

    @Test void testArrayOfArrays_shouldReturnTheMinAvgOfAllArraysInsideMainArray(){
        Library sut = new Library();
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int result= arrayOfArrays(arr);
        Assertions.assertEquals(61,result);
    }


}
