/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static basiclibrary.Library.*;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
//

    @Test void testRoll_shouldReturnArrayOfSizeEqualToParameter(){
        Library sut = new Library();
        int x=4;
        ArrayList<Integer> result= roll(x);
        assertEquals(4, result.size());

        // Validate each rolled number falls within the range [1, 6]
        for (Integer rolledNumber : result) {
            assertTrue(rolledNumber >= 1 && rolledNumber <= 6);
        }

    }
    @Test void testContainsDublicate_shouldReturnTrueIfArrayHasDuplicatedValue(){
        Library sut = new Library();
        int arr[]={1,2,5,8,1};
        boolean result = containsDuplicate(arr);
        Assertions.assertEquals(true,result);
    }
    @Test void testCalculateAvg_shouldReturnAvgOfArray(){

        Library sut = new Library();
        int arr[]={66, 64, 58, 65, 71, 57, 60};
        double result = calculateAverage(arr);
        Assertions.assertEquals(54,result);

    }

    @Test void testArrayOfArrays_shouldReturnTheMinAvgOfAllArraysInsideMainArray(){
        Library sut = new Library();
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int result= arrayOfArrays(arr);
        Assertions.assertEquals(61,result);
    }

    @Test void tally_shouldReturnTheNameHasMaxVotes(){
        Library sut = new Library();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String result =sut.tally(votes);
        Assertions.assertEquals("Bush",result);

    }


    @Test void checkWeather_returnHighestAndLowestAndNeverSawTemp() {
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outputStream));

        sut.checkWeather(weeklyMonthTemperatures);

        String expectedOutput = "High : 72\n" +
                "Low : 51\n" +
                "Never Saw temp : 63\n" +
                "Never Saw temp : 67\n" +
                "Never Saw temp : 68\n" +
                "Never Saw temp : 69\n";
        assertEquals(expectedOutput, outputStream.toString().replace("\r\n", "\n"));
    }


}
