/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

public class App {
    public static void main(String[] args) throws IOException {
        Path filePath = Path.of("C:/Users/USER/newforGradle/Java-fundamentals/linter/app/src/test/resources","/gates.js");
        checkFile(filePath);
    }
    public static void checkFile(Path filePath) {
        try (BufferedReader reader = Files.newBufferedReader(filePath)) {
            String line;
            int lineNumber = 0;
            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (!line.isEmpty()) {
                    if (!line.trim().endsWith(";") && !line.trim().endsWith("{") && !line.trim().endsWith("}")
                            && !line.contains("if") && !line.contains("else")) {
                        System.out.println("Line " + lineNumber + ": Missing semicolon.");
                    }}
            }
        } catch (IOException e) {
            System.out.println("Error reading file: " + e.getMessage());
            e.printStackTrace();
        }
    }

}
